cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'pyton'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'nginx'
brew 'nvm'
brew 'macvim'

cask 'handbrake'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
cask 'docker'
cask 'virtualbox'
cask 'postman'
cask 'sequel-pro'
cask 'slack'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'firefox'
cask 'iterm2'
cask 'visual-studio-code'
cask 'spotify'